# 1 Set master image
FROM php:8.2-fpm-alpine

# 2 Set working directory
WORKDIR /var/www/html

# 3 Install Additional dependencies
RUN apk update && apk add --no-cache \
build-base shadow vim curl \
php8.2 \
php8.2-fpm \
php8.2-common \
php8.2-pdo \
php8.2-pdo_mysql \
php8.2-mysqli \
php8.2-mcrypt \
php8.2-mbstring \
php8.2-xml \
php8.2-openssl \
php8.2-json \
php8.2-phar \
php8.2-zip \
php8.2-gd \
php8.2-dom \
php8.2-session \
php8.2-zlib

# 4 Add and Enable PHP-PDO Extenstions
RUN docker-php-ext-install pdo pdo_mysql mysqli
RUN docker-php-ext-enable pdo_mysql

# 5 Install PHP Composer
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# 6 Remove Cache
RUN rm -rf /var/cache/apk/*

# 7 Add UID '1000' to www-data
RUN usermod -u 1000 www-data

# 8 Copy existing application directory permissions
COPY --chown=www-data:www-data . /var/www/html

# 9 Change current user to www
USER www-data

# 10 Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
